[project]
name = "gel-auth-fastapi"
version = "0.1.0"
description = "Gel auth extension binding for FastAPI"
readme = "README.md"
authors = [
    { name = "Gel Data Inc.", email = "hello@geldata.com" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115",
    "gel[auth]",
    "pyjwt>=2.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
gel = { git = "https://github.com/geldata/gel-python", branch = "auth" }

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.9.7",
]

[tool.mypy]
exclude = [
    "^.venv",
    "^.eggs",
    "^.github",
    "^.vscode",
    "^build",
    "^dist",
    "^docs",
    "^target",
    "^examples",
]
files = "."
python_version = "3.9"
ignore_missing_imports = true

[tool.ruff]
line-length = 80
indent-width = 4

[tool.black]
line-length = 80
target-version = ["py39", "py310", "py311", "py312", "py313"]
