name: Test FastAPI bindings

on:
  push:
    branches:
      - main
    paths:
      - "python-fastapi/**"
  pull_request:
    branches:
      - main
    paths:
      - "python-fastapi/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-fastapi
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run python -m unittest discover -s tests -v

  find-examples:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Find all examples to test
        id: set-matrix
        working-directory: python-fastapi
        run: |
          examples=$(find examples -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
          if [ -z "$examples" ]; then
            echo "No examples found"
            examples="[]"
          else
            examples=$(echo $examples | jq -R 'split(" ")' | jq -c '.')
          fi
          matrix=$(jq -c -n --argjson examples "$examples" '{example: $examples}')
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

  test-examples:
    runs-on: ubuntu-latest
    needs: find-examples
    strategy:
      matrix: ${{fromJson(needs.find-examples.outputs.matrix)}}
    defaults:
      run:
        working-directory: python-fastapi/examples/${{ matrix.example }}
    steps:
      - uses: actions/checkout@v4

      - name: Load Python version from .python-version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Test "${{ matrix.example }}"
        run: uv run python -m unittest -v
